name: Github Python 3.10.18 3.12.11 3.13.5
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.18 3.12.11 3.13.5
      uses: actions/setup-python@v5
      with:
        python-version: |
          3.10.18
          3.12.11
          3.13.5
    - name: Install dependencies
      run: |
        make install
    - name: Lint
      run: |
        make lint
    - name: Test
      run: |
        make test
    - name: Format
      run: |
        make format